document.addEventListener('DOMContentLoaded',()=>{initThemeToggle();initScrollSpy();initOKRTabs();initPendingItemsFilter();initCharts()});
function initThemeToggle(){const b=document.getElementById('themeToggleBtn');if(!b)return;const t=localStorage.getItem('theme')||'dark';document.documentElement.setAttribute('data-theme',t);u(b,t);b.addEventListener('click',()=>{const c=document.documentElement.getAttribute('data-theme');const n=c==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',n);localStorage.setItem('theme',n);u(b,n)})}
function u(b,t){b.innerHTML=t==='dark'?'☀️ 淺色模式':'🌙 深色模式'}
function initScrollSpy(){const s=document.querySelectorAll('.section');const l=document.querySelectorAll('.nav-link');window.addEventListener('scroll',()=>{let c='';s.forEach(x=>{if(pageYOffset>=x.offsetTop-100)c=x.id});l.forEach(x=>{x.classList.remove('active');if(x.getAttribute('href')==='#'+c)x.classList.add('active')})})}
function initOKRTabs(){const bs=document.querySelectorAll('.okr-tab-btn');const cs=document.querySelectorAll('.okr-card');bs.forEach(b=>b.addEventListener('click',()=>{bs.forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=b.getAttribute('data-division');cs.forEach(c=>{c.style.display=(d==='all'||c.getAttribute('data-division')===d)?'block':'none'})}))}
function initPendingItemsFilter(){const s=document.getElementById('pendingSearchInput');const p=document.getElementById('priorityFilter');const r=document.querySelectorAll('.pending-item-row');if(!s||!p)return;function f(){const q=s.value.toLowerCase();const v=p.value;r.forEach(row=>{const t=row.textContent.toLowerCase();const pr=row.getAttribute('data-priority');row.style.display=(t.includes(q)&&(v==='all'||pr===v))?'':'none'})}s.addEventListener('input',f);p.addEventListener('change',f)}
function initCharts(){if(typeof Chart==='undefined')return;
// Chart 1: Foxconn parallel — Three-layer resource allocation
const c1=document.getElementById('layerChart')?.getContext('2d');
if(c1){new Chart(c1,{type:'doughnut',data:{labels:['強中央 (資本配置/數據/技術/孵化)','富地方・建坤 SPV','富地方・維運事業','富地方・ATMOCE','孵化層・綠電售電業','孵化層・AIDC','孵化層・CPO'],datasets:[{data:[25,15,15,15,10,10,10],backgroundColor:['#8b5cf6','#10b981','#059669','#047857','#06b6d4','#0284c7','#0891b2']}]},options:{responsive:true,plugins:{legend:{position:'right',labels:{color:'#9ca3af',font:{size:11}}},title:{display:true,text:'強中央富地方三層組織資源分配架構',color:'#9ca3af'}}}})}
// Chart 2: 3+3 Framework
const c2=document.getElementById('threeThreeChart')?.getContext('2d');
if(c2){new Chart(c2,{type:'bar',data:{labels:['AI 算力供電','交通電氣化','韌性電力'],datasets:[{label:'未來產業 (需求端)',data:[90,60,80],backgroundColor:'#06b6d4',borderRadius:6},{label:'核心技術支撐度',data:[75,40,85],backgroundColor:'#10b981',borderRadius:6}]},options:{responsive:true,indexAxis:'y',plugins:{legend:{position:'bottom',labels:{color:'#9ca3af'}},title:{display:true,text:'3+3 三大未來產業 × 核心技術匹配度 (示意)',color:'#9ca3af'}},scales:{x:{ticks:{color:'#9ca3af'}},y:{ticks:{color:'#9ca3af'}}}}})}
// Chart 3: O&M coverage
const c3=document.getElementById('omChart')?.getContext('2d');
if(c3){new Chart(c3,{type:'bar',data:{labels:['台南/高雄/屏東 (P0)','彰化/雲林/嘉義 (P1)','桃園/新竹/苗栗 (P2)','東部/離島 (P3)'],datasets:[{label:'據點需求 (站)',data:[3,2,1,0],backgroundColor:['#10b981','#06b6d4','#3b82f6','#9ca3af'],borderRadius:6}]},options:{responsive:true,plugins:{legend:{display:false},title:{display:true,text:'維運事業區域據點規劃 (加盟 + 自建混合)',color:'#9ca3af'}},scales:{y:{ticks:{precision:0,color:'#9ca3af'}},x:{ticks:{color:'#9ca3af'}}}}})}
}
